[[redirects]]
from = "/historia"
to = "/history"
status = 301
force = false
[[redirects]]
from = "/presentes"
to = "/giftlist"
status = 301
force = false
[[redirects]]
from = "/local"
to = "/place"
status = 301
force = false
[[redirects]]
from = "/padrinhos"
to = "/bestmans"
status = 301
force = false
[[redirects]]
from = "/presentes"
to = "/giftlist"
status = 301
force = false
[[redirects]]
from = "/galeria"
to = "/gallery"
status = 301
force = false
[[redirects]]
from = "/obrigado"
to = "/thanks"
status = 301
force = false
